import type { Metadata } from "next";
import "./globals.css";
import { titilliumWebRegular } from "./util/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${titilliumWebRegular.className} antialiased no-scrollbar`}
      >
        {children}
      </body>
    </html>
  );
}
